### ISSUE TITLE
filter blocking too much

### ISSUE THREAD

**Issue by ylvarw** [DandelionSprout/adfilt#1008]
Hello!

You currently have a block for Prisjakt in your blockList
this is a comparison site and the CDN does not contain any ads
this filter is currently blocking some shops from being able to display their shop rating widget

from what I see there is several rows in the blocklist affecting this, added one example : 
https://github.com/DandelionSprout/adfilt/blob/1a8b3878271320deef182fac384989bdc40741dc/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP-Inclusion.txt#L5418

**Comment by DandelionSprout** [comment]
Likely the result of the Swedish entries' sources. I'll come up with something.

**Comment by DandelionSprout** [comment]
I've now removed the 3 most obvious one that I couldn't attest to the presence of ads on (`pji.nu`, `prisjakt-a` and `pricespy-75b8.kxcdn.com`). I'm keeping `prisjakt.nu` for the time being since I know it's used for carousels on newssite frontpages.

As a possible bonus, in part because my ABP/AdBlock list converts some entries from his, you can try your luck at reporting any remaining stuff to https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt, but his list goes far, far further to block trackers and cookie notices than I do.

**Comment by ylvarw** [comment]
Thank you very much for the help, and thanks for a quick response as well
