### ISSUE TITLE
Anti-Malware false positive: catpawdesk.top

### ISSUE THREAD

**Issue by Codfish246** [DandelionSprout/adfilt#1043]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

http://catpawdesk.top is blocked by Dandelion Sprout's Anti-Malware List

### Add a screenshot of the extension's logger

![image](https://github.com/DandelionSprout/adfilt/assets/23464269/1c12ee9f-8788-45f0-88e5-7cb22109e40c)

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

AGH Version v0.107.51

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

OISD, CERT Polska, Dandelion Sprout's Anti-Malware List

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

Developer Edition/Beta

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

24H2

**Comment by iam-py-test** [comment]
It is hard to verify the safety of this website without access to the program it promotes.
Thanks

**Comment by DandelionSprout** [comment]
On the day this was originally reported, I remember clicking on the link and my Chrome setup claimed the connection had timed out. But since Hurricane Electric BGP had in contradiction got the front page to load, I didn't mention my problems at the time. 😓

This time around it leads to https://samperson.itch.io/desktop-cat-cursor, which ironically makes `catpawdesk.top` less likely to be whitelisted, since there's been previous precedences of not whitelisting domains that are immediate redirections.

**Comment by Codfish246** [comment]
It does indeed lead to [https://samperson.itch.io/desktop-cat-cursor](https://samperson.itch.io/desktop-cat-cursor) I believe, but it's understandable if a redirect doesn't warrant a whitelist
