### ISSUE TITLE
Host list AntiMalwareHosts.txt, 8 invalid entries

### ISSUE THREAD

**Issue by RichardBeisser** [DandelionSprout/adfilt#1046]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hello,
File AntiMalwareHosts.txt is a Host-List, but it contains non-domain entries:

  [i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 23503 exact domains and 0 ABP-style domains (ignored 8 non-domain entries)
      Sample of non-domain entries:
        - "5.8.47.3"
        - "190.238.183.5"
        - "85.239.33.9"
        - "113.116.89.1"
        - "182.116.104.6"

### Which adblocker(s) did you use when testing this?

Pi-hole (Support may be limited)

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

-----

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

-----

### Which OS(s) did you use when testing this?

Windows 11

**Comment by iam-py-test** [comment]
[This is intentional](https://github.com/DandelionSprout/adfilt/issues/919#issuecomment-1734527953):
> I remember faintly from around 2020 that IPs in the domains list version was intentional, just in case someone tried to use that list version with software that supported IP blocking. On top of that, non-existent community communication by Pi-hole devs meant I couldn't rule out that Pi-Hole supported such IP blocking.
> 
> As it stands, I'm inclined to let the IPs remain, but could reconsider if any domains blocking tools out there were to discard entire lists with unsupported entries (There was a similar incident involving DNSMASQ last week).

Thank you
<details>
<summary>Related</summary>
<code>!</code> is not a valid comment, but the commented out TLDs appear as
<blockquote>
!!!||ooo<br>
!!!||monster<br>
!!!||sbs<br>
!!!||discount<br>
!!!||cfd</blockquote>
</details>

**Comment by DandelionSprout** [comment]
While I admit that there was no 100% certain answer to the report's core question (Whether IP addresses should be in a hostfile), I began recommending sometime after the report was opened that Pi-hole users should use https://raw.githubusercontent.com/DandelionSprout/adfilt/refs/heads/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt instead of the hostfile version.

The way I understood things (The Pi-hole devs have completely non-existent interactivity with any other adblocking communities), Pi-hole (re?)introduced support for `||`-type entries in v5.22 (`||`-type entries usually doesn't run into errors with IP addresses), and I take an unqualified guess that most Pi-hole users have updated to that version or higher by now.
