### ISSUE TITLE
The website mcpedl.com becomes mostly unusable when using the Annoyances filterlist due to the blockage of "smartbanner.js"

### ISSUE THREAD

**Issue by legendary-creeper** [DandelionSprout/adfilt#1065]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

The entire [mcpedl.com](https://mcpedl.com/) site becomes unusable when "smartbanner.js" is being blocked. Images and other resources do not load. ReCaptcha loads indefinitely, and other unintended behavior occurs.

This issue is resolved if you apply the following rule in your personal filter:

`.smartbanner.js$badfilter`

### Add a screenshot of the extension's logger

![image](https://github.com/user-attachments/assets/31bf338c-12c0-495b-a614-c5a53fe5dcb1)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.60.0

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList

### Which browser(s) did you use when testing this?

Brave Browser

### Browser version(s)

1.70.126

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Linux Mint 22 Cinnamon

**Comment by DandelionSprout** [comment]
`.smartbanner.js` is typically used to block various "Download our app" banners on many other sites, but I'll certainly take a look later tonight into how `mcpedl` are using scripts with such names.

**Comment by Tmp341** [comment]
I don't have any problem here (except that huge space above articles):
```
uBlock Origin: 1.60.0
Firefox: 131
Windows 10 x64
```
![1](https://github.com/user-attachments/assets/e7c6146b-0ebc-4172-b7c9-ccbaad67fb19)

**Comment by DandelionSprout** [comment]
Makes me think about that far from all issue reports I receive for my lists have screenshots of the reported pages. I was eventually able to find larger problems on one of the gamemods' pages (Tested with `https://mcpedl.com/slime-ii/`), where the problem is pretty big:

<details><summary>With `.smartbanner.js`:</summary>

![image](https://github.com/user-attachments/assets/0a62bc11-b79e-4e02-a490-87d5057b0b22)

</details>

<details><summary>When whitelisting `.smartbanner.js`:</summary>

![image](https://github.com/user-attachments/assets/f7a0f0e1-12cc-417f-9e28-db53f028a7cf)

</details>

After thinking about my options, I'll go with changing the `.smartbanner.js` entry into `.smartbanner.js$domain=~mcpedl.com`, which seems to work in my tests.
