### ISSUE TITLE
fdroid.bromite.org Blocked @ Dandelion Sprout's Anti-Malware List

### ISSUE THREAD

**Issue by Alex9001** [DandelionSprout/adfilt#1075]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

bromite's fdroid repo is being blocked

### Add screenshots below if needed

![image](https://github.com/user-attachments/assets/d6816d5f-1136-4773-af70-a03b76638b97)

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Adblocker version(s)

v0.107.54

### Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.

Dandelion Sprout's Anti-Malware List

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Browser version(s)

latest

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

arch btw

**Comment by DandelionSprout** [comment]
It was initially blocked due to #1059 and https://github.com/hagezi/dns-blocklists/pull/3848, where there were worries that BromiteORG would've become a hijacked domain sometime last month (October).

Based on SecurityTrails, it seems it in fact did technically end up hijacked ("Sedo" doesn't *sound* like a particularly trustworthy host), though it did not become malware outright:

![image](https://github.com/user-attachments/assets/6d5aecef-fe91-4168-9b7e-190787a4d747)

Even more strangely, it appears the domain was bought back 4 days later to the same ISP (Fastly) and website look as before; so this situation is strange for me to figure out, to say it the least.

**Comment by DandelionSprout** [comment]
Having considered my options, and seeing that there's nothing on the current resurrection of their site that even resemble rogue scripts, I will agree to remove that blocking entry pretty soon now.
