### ISSUE TITLE
Overblocking: IKEA (and probably some german organization websites)

### ISSUE THREAD

**Issue by HorayNarea** [DandelionSprout/adfilt#149]
https://github.com/DandelionSprout/adfilt/blob/075eac2270d48b0ca2901135ca0dfd6bbbe4e379/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L410

This line blocks some IKEA sites, for example their app [IKEA Home smart (TRÅDFRI)](https://apps.apple.com/us/app/ikea-home-smart-tr%C3%A5dfri/id1195836071) has a "View update details" link where you can see the changelog of TRÅDFRI firmware updates, which is hosted on `ww8.ikea.com`:

![20-12-08 04-28-21 1979](https://user-images.githubusercontent.com/1871153/101436605-c4434380-390e-11eb-8cf6-c5e504c20d0e.png)

![20-12-08 04-28-26 1980](https://user-images.githubusercontent.com/1871153/101436610-c60d0700-390e-11eb-9432-70a73f317123.png)

![Screenshot from 2020-12-08 04-20-29](https://user-images.githubusercontent.com/1871153/101435595-e76cf380-390c-11eb-9d3b-c17530315c2e.png)

---

Acutally quite a few official sites of german organizations (like some internal sites of universites, some schools, etc.) use `ww[0-9].organization.de` so these rules will probably also overblock them¹

¹ yeah I know, that is stupid and they should use real loadbalancing or something… but that's how it is :roll_eyes:

**Comment by DandelionSprout** [comment]
Removing these entries are not a realistic option, due to them being used to block "sites" like these: 
![image](https://user-images.githubusercontent.com/22780683/101463313-8c072980-393d-11eb-9987-ad5f6975af6a.png)
![image](https://user-images.githubusercontent.com/22780683/101464491-fff60180-393e-11eb-9d91-e968e7ee5417.png)

And `https://www.google.com/search?q=site%3Aww8.*.de&start=0&sa=N` shows that the bad uses of `://www8.` heavily outnumber the legitimate uses even in Germany, at least on non-intranet sites.

Writing whitelistings is going to take me a couple days, but I've got few or no other functional ways to fix this.

**Comment by HorayNarea** [comment]
Yeah looks like there is really an enormous amount of bad domains and I only know of 3 legitimate domains of which only the IKEA-domain is public enough to be included (well, excluded :D) in this list :/

So, this issue can be closed when the IKEA domain is whitelisted.
