### ISSUE TITLE
Dead domain

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#218]
https://github.com/DandelionSprout/adfilt/blob/d4b2936728686407db6211f6beb979fd2e756771/Android%20Scum%20Class%20%E2%80%94%20Fake%20notification%20counters.txt#L89
The rule above seems to referencing a dead domain.
When visited or pinged, I get an error:
![image](https://user-images.githubusercontent.com/84232764/124610515-94c1ce80-de3e-11eb-9f1b-242bde0a3f90.png)

Tested with outside tools and in-and-outside of a VM, and it still can not be reached.

Update: When accessed via Tor, I now get a 404 error. I don't know why I can't access it otherwise

**Comment by DandelionSprout** [comment]
I can assure you 110% that it's a legitimate and active site. But since it's a login site for banks, there are a whole lot of security measures involved. As for the bank that I myself use, `https://id.portalbank.no/wsl/slogin/Run?n_bank=4230` is a valid starting-point URL. 
![image](https://user-images.githubusercontent.com/22780683/124630291-9319fa00-de82-11eb-9b36-2679b9b8feb9.png)

**Comment by iam-py-test** [comment]
> I can assure you 110% that it's a legitimate and active site. But since it's a login site for banks, there are a whole lot of security measures involved. As for the bank that I myself use, `https://id.portalbank.no/wsl/slogin/Run?n_bank=4230` is a valid starting-point URL.
> ![image](https://user-images.githubusercontent.com/22780683/124630291-9319fa00-de82-11eb-9b36-2679b9b8feb9.png)

Ok.
I think it may be that I am in the US, so they don't let me access it.
I am very sorry for wasting your time

**Comment by krystian3w** [comment]
Maybe the best "google" page in web search.

In Poland works good links from Google like:

`https://www.portalbank.no/2230/nettbank/`
