### ISSUE TITLE
Twitter de-politicator might block JS libraries

### ISSUE THREAD

**Issue by theel0ja** [DandelionSprout/adfilt#22]
https://github.com/DandelionSprout/adfilt/blob/0542b37603fd85f2ca7249354953e2b8dc75603a/Twitter%20De-Politificator.txt#L20-L21

URL: https://twitter.com/search?q=js%20libs

tweets about programming can be found

![screenshot_20190113_165956](https://user-images.githubusercontent.com/5832930/51086911-2c4d7700-1744-11e9-90e5-fe75a8f6f7e0.png)

![screenshot_20190113_170302](https://user-images.githubusercontent.com/5832930/51086923-543cda80-1744-11e9-89f9-2cb92f5d7dbe.png)

**Comment by theel0ja** [comment]
Btw I would add "dems" to the list, because many of the non-programming tweets that contain word "libs" contain also "dems"

**Comment by DandelionSprout** [comment]
Those are both actually pretty good and valid points. I'll make sure to edit the list right away to accomodate to them.

After all, the list is marked as Alpha for a reason, as it's pretty underdeveloped and untested. So that means that the list is even more open for suggestions than it'd otherwise be.

**Comment by theel0ja** [comment]
I also would add that communist symbol to the list (similarly to Nazi symbol), because most of the tweets (I'd say 90+%) with it as username or content are political.
