### ISSUE TITLE
[DandelionSprout DNS] Add new blocklists

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#242]
Please consider adding https://gitlab.com/curben/urlhaus-filter, https://gitlab.com/curben/pup-filter, and https://gitlab.com/curben/phishing-filter
These lists are all maintained by https://gitlab.com/curben, and all seem fairly good blocklists.
Also, you might want to look at https://github.com/blocklistproject/Lists as they have some good blocklists for ads and malware.
Thanks for providing a free DNS. I will add it to all of my devices as soon as I can figure out how to

**Comment by DandelionSprout** [comment]
Phishing Filter seems fairly good. And so do PUP Filter, although that list is a bit small.

For URLhaus Filter, I'm just a bit perplexed by how 85% of its entries are IPs, even if that would technically make the list a *stellar* fit for AdGuard Home.

I'll see if I can remember to add Phishing Filter tomorrow, at the very least.

**Comment by DandelionSprout** [comment]
After I successfully added Phishing Filter, I stumbled across at least one problem with its IP entries: https://gitlab.com/curben/phishing-filter/-/issues/9 (although I have added a whitelist entry in Falukorv List in the meantime).

Since I'll head out on vacation on Tuesday or Wednesday, which'll make it 30 times harder for me to look into AdGuard Home logs, I lack the time and energy needed to add and then sort out any major issues related to URLhaus Filter or PUP filter. As such, I'll declare this a closed case for now, with the possibility of re-opening it in 2 weeks' time.

**Comment by iam-py-test** [comment]
@DandelionSprout what are the criteria for adding a new list?

**Comment by DandelionSprout** [comment]
My main priorities for that server this week, have been to:
• Invest in and set up a new router to hopefully reduce the number of outages.
• Figuring out the best time to bump https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/881 again.

Accordingly, adding new lists have not been a high priority in the past few weeks.

**Comment by iam-py-test** [comment]
@DandelionSprout understood
