### ISSUE TITLE
Broken link in the "I wish to help" form

### ISSUE THREAD

**Issue by iam-py-test** [DandelionSprout/adfilt#263]
The _I wish to help_ form includes a link to another of the fake uBo variants:
![image](https://user-images.githubusercontent.com/84232764/132060689-4a4b705e-db19-4958-9210-98878d2286e9.png)
[The link](https://chrome.google.com/webstore/detail/adblock/dgpfeomibahlpbobpnjpcobpechebadh) returns a 404, probably because Google took it down.

**Comment by DandelionSprout** [comment]
Good point. I suppose that link (or even that entire option) can be safely removed now, then.

**Comment by iam-py-test** [comment]
@DandelionSprout you might want to add uBlock Origin to the list of AdBlockers

**Comment by DandelionSprout** [comment]
The situation is a bit complicated with that form, as it was made a time when I was a one-man army who could handle *all* uBO and AdGuard matters on my own, and that I merely needed some help with correcting syntaxes for very unusual adblockers.

Times sure have changed, since stuff like adding entries to Legitimate URL Shortener now takes me up to 2 weeks due to frequent fevers. I'll have to announce an "Assistant(s) wanted" announcement of sorts to ask for repo assistants for 3 or 4 of my lists.

**Comment by iam-py-test** [comment]
@DandelionSprout I am willing to help out with the repo (i.e. using PRs)
I am at school most of the day, but can still spend time working on it

**Comment by DandelionSprout** [comment]
In that case it seems to bes your lucky day if you can document a good prior history of contributing to various repos: https://github.com/DandelionSprout/adfilt/issues/264
