### ISSUE TITLE
behance.net

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#30]
The lower right corner:

![obraz](https://user-images.githubusercontent.com/35370833/52535253-492d9800-2d4c-11e9-90af-2587db9d4067.png) | ![obraz](https://user-images.githubusercontent.com/35370833/52535261-5a76a480-2d4c-11e9-990b-db0bc38f7fa4.png)
--- | ---

---

`##.BPaidTYo1hlmhIB4OaH01._2RAh0H_ZxrBlIkNqK3A0Dw.T3FwtjydI3ejKLFSEY9kO`

Another random...

**Comment by krystian3w** [comment]
`#?#body > div[class]:last-child:-abp-has(>div>div>.js-adobeid-signup)`

Maybe safe.

**Comment by DandelionSprout** [comment]
Due to its relatively small size, that it can be closed with ease, and that it doesn't seem to show up on small screens or on phones, I had to think for some minutes about whether it was actually worth it to add to *Browse Websites Without Logging In*.

But I guess I have nothing too big to lose by adding it.

**Comment by DandelionSprout** [comment]
With the entry having been added, the issue will now be marked as "Closed".
