### ISSUE TITLE
Google ads on phone

### ISSUE THREAD

**Issue by Schanzation** [DandelionSprout/adfilt#37]
Hello!

I own a OnePlus 7. Using Firefox Nightly on my phone with uBlock Origin 1.20.0 installed and getting ads on google searches. Any idea how to block them? I get ads on google using Brave also.

https://imgur.com/a/0xpY6N5

**Comment by DandelionSprout** [comment]
Unfortunately I seem to be unable to reproduce the problem, but what I at least can suggest for you is to try out https://addons.mozilla.org/firefox/addon/google-search-fixer/, which aims to create a fake user-agent that makes Google Search load the more maintained Chrome Android page versions instead of the Firefox for Android page versions.

**Comment by Schanzation** [comment]
The search results look sorta different but it did remove ads on all my search results. Thanks!
