### ISSUE TITLE
Anti-Astrology List Breaks Mastodon

### ISSUE THREAD

**Issue by bkrucarci** [DandelionSprout/adfilt#487]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Anti-Astrology List Breaks Mastodon, please check witht he following website. I also made a video which shows the problem.
https://mastodon.social/@inziva/107537637479119903

### Add screenshots below if needed

Video : https://recordit.co/nAnQw3hMJu

### Add a screenshot of the extension's logger

N/A

### Which adblocker(s) did you use when testing this?

AdGuard (for browsers)

### Adblocker version(s)

4.0.105 Beta

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

AdGuard's Base + Tracking + Turkish &
Dandelion's Anti-Prayer TimerList
Dandelion's Anti-Astrology List
Dandelion's I do not want to download your browser list
Dandelion's Browse websites without logging in

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

96.0.3

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

Pro 21H1

**Comment by DandelionSprout** [comment]
The problem is the result of 2 problems on AdGuard's part that defy any known logic:

* In the entry `mastodon.*,mstdn.*,mas.to,pawoo.net,fosstodon.org,fandom.ink,tchncs.de,octodon.social,sinblr.com,baraag.net,xxxtumblr.org#?#.entry,.statuses-grid__item,.status__wrapper:-abp-contains(/Pisces/i)`, AdGuard blocks all instances of `.entry` and `.statuses-grid__item`, whereas uBO and ABP make all three of them subject to `:-abp-contains`
* AdGuard still doesn't recognise `!#if` values in custom filters, some 4 years after they were supposed to add support for them.

Accordingly, I'm genuinely unsure how to best fix this problem.

**Comment by bkrucarci** [comment]
Wow! what did i find 💯 Thanks for reporting this to AdGuard
