### ISSUE TITLE
{Question} Can "Actually Legitimate URL Shortener Tool" work as good as ClearURLs Add-on?

### ISSUE THREAD

**Issue by Paras6408** [DandelionSprout/adfilt#716]
Just asking because of curiosity since I have ClearURLs did better job but it breaks some sign-ins.

**Comment by iam-py-test** [comment]
Honestly, I don't know. In my opinion, Legit URL is better because it is updated far more often and seems to have less breakage, but clearly I am biased.
There is a "ClearURLs for uBlock Origin" (and AdGuard) list made by me (and rusty-snake), but it breaks a lot of websites and is _pretty much_ the same as ClearURLs.

**Comment by DandelionSprout** [comment]
*Actually Legitimate URL Shortener Tool* has something like 6 times as many entries (though I haven't doublechecked in a long time) and would on paper work better.

**Comment by iam-py-test** [comment]
> Actually Legitimate URL Shortener Tool has something like 6 times as many entries

Going on the uBo entry counters, Legit URL has 1363 more entries than ClearURLs for uBo. Going by a poorly-written Python script, Legit has 1361 more, so it's probably somewhere in that general area. (My math says 3ish times more, but I'm probably wrong.)
Size isn't equal to quality of course.

**Comment by iam-py-test** [comment]
Given that the question has been answered and the OP has not responded, I am closing this issue. The comments remain open
