### ISSUE TITLE
[Whitelist] jpg.church site

### ISSUE THREAD

**Issue by nightznero** [DandelionSprout/adfilt#769]
I noticed is the latest filter list that I'm using and still blocks `jpg.church `
`jpg.church ` is a image host service,like imgur. Would be nice to whitelist that site.

Best regards!

**Comment by DandelionSprout** [comment]
It is most likely caused by [a very outdated and deprecated subfile](https://github.com/DandelionSprout/adfilt/blob/master/Sensitive%20lists/uBO%20list%20extensions/AntiPreacherList-AdblockerExtension.txt) included in *Anti-Preacher List* that I simply haven't figured out how to handle nowadays. I'll add a whitelisting for the domain ASAP, at least.

**Comment by nightznero** [comment]
> It is most likely caused by [a very outdated and deprecated subfile](https://github.com/DandelionSprout/adfilt/blob/master/Sensitive%20lists/uBO%20list%20extensions/AntiPreacherList-AdblockerExtension.txt) included in _Anti-Preacher List_ that I simply haven't figured out how to handle nowadays. I'll add a whitelisting for the domain ASAP, at least.

Idk that screen i posted just gone or smthg but 😅 issue still exist, [AdGuard Home List](https://github.com/DandelionSprout/adfilt/blob/160b4ea6fba0e1a9ca962e1bbec490fa6b3e8017/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList.txt#L11110)

**Comment by DandelionSprout** [comment]
Oh, okay, *that* list. I'll see if I can manage to squeeze in a major update of that list this morning.
