### ISSUE TITLE
Is it redundant to use EasyList also?

### ISSUE THREAD

**Issue by Mellbourn** [DandelionSprout/adfilt#770]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

This is more of a question: When using this list, is it redundant to have EasyList enabled also?

I'm asking because of the options in Adblock Plus. When I add this filter it is listed as
`norsk, dansk, íslenska, føroyskt, kalaallisut, svenska, suomi + English (Dandelion Sprout's Nordic Filters+EasyList)`

Noting the `+EasyList` does this mean that this list contains the entire content of EasyList, thereby making it redundant?

If yes, how often is this list synced with EasyList?

### Add screenshots below if needed

<img width="704" alt="image" src="https://user-images.githubusercontent.com/1785727/216669236-61cbfeeb-73f6-42e4-94fb-4ebc4a629dd7.png">

### Which adblocker(s) did you use when testing this?

Adblock Plus (Firefox or Manifest V2)

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

EasyList and yours

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

**Comment by DandelionSprout** [comment]
Due to the way Adblock Plus builds up and hosts their included lists, it is indeed superfluous to use both in ABP. Essentially, the ABP servers fetch my list (which is mostly hosted on GitHub), and combine it with EasyList on their own company servers. As a result of that, syncing seems to happen every 2 hours or so.

All of this is in stark contrast to other adblockers I've come across, which fetch regional lists directly from their sources without any combining.

**Comment by Mellbourn** [comment]
Thank you for your quick answer and your great list!
