### ISSUE TITLE
Question: Help hide Advertisement text in a page.

### ISSUE THREAD

**Issue by 54m4d** [DandelionSprout/adfilt#784]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Hello Imre

Maybe this is kind of out of topic since not related to your lists, but i just want to check if you have any tips on how to hide this `Advertisement` word on these [articles](https://www.ghacks.net/2023/02/04/its-just-two-months-after-chatgpts-launch-and-it-already-has-100-million-users/)?

### Add screenshots below if needed

![image](https://user-images.githubusercontent.com/52612348/219705133-f4014bb2-25b6-42c6-9d44-670fe9b61219.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.46.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock default + some Dandelion Sprouts' Lists but the issue isn't related to any lists since it's a plain text.

### Which browser(s) did you use when testing this?

Google Chrome (Manifest V2)

### Browser version(s)

110.0.5481

### Which OS(s) did you use when testing this?

Windows 10

**Comment by DandelionSprout** [comment]
You ask politely enough that I would've helped you, but that one text string has been infamously difficult to remove for years, since browsers generally don't offer the ability to remove inline text strings (which look like these in the F12 DevTools) with any conventional means: 
![image](https://user-images.githubusercontent.com/22780683/219706619-5bf77ba7-9c02-4b71-a773-bd71981d1e9d.png)

**Comment by iam-py-test** [comment]
I think you could ask (in the future) at https://github.com/DandelionSprout/adfilt/discussions/779

**Comment by 54m4d** [comment]
> I think you could ask (in the future) at #779

Should we continue there?

**Comment by 54m4d** [comment]
Moved to discussions
