### ISSUE TITLE
Not just an "adfilt": there are also the filters for political and other reasons. Rename a repository to i.e. sitefilt?

### ISSUE THREAD

**Issue by informer2016** [DandelionSprout/adfilt#80]
Seeing there are the filters for political and other reasons, maybe it's a good idea to rename a repository from adfilt to i.e. sitefilt or something like that. The current "adfilt" name is misleading: a user may install it for the purpose of advertisement blocking, but then discover that some websites (i.e. political) blocked simply for contradicting with your personal point of view - refuse to load.

**Comment by DandelionSprout** [comment]
While I see your point, my current personal impression is that there's no known cases of such a mistake having occured. This is mostly because I presume that ≥97% who subscribe to my non-ad-nor-malware lists do so through https://filterlists.com/, which heavily downplays the repo names in favour of the lists' proper titles.

Renaming the entire repo would sadly also (to the best of my knowledge) break every single link out there to my lists.
