### ISSUE TITLE
Enhancement: Instructions for use in readme

### ISSUE THREAD

**Issue by ibex-are-goats** [DandelionSprout/adfilt#84]
Hello! I see all these interesting files, but I don't know how to use them. For example, I added this link to my unblock origin list, and it does nothing: https://github.com/DandelionSprout/adfilt/blob/master/TwitchPureViewingExperience.txt

Can you add instructions for how to use these files to the readme? Thanks!

**Comment by DandelionSprout** [comment]
Adblockers can generally only use the completely raw versions of text files. To reach those versions on GitHub, while you're at the kind of page that you linked to above, click on the "Raw" button in the upper right. This'll lead you to the raw file version hosted at `raw.githubusercontent.com`, and it's that version whose link should be pasted into the uBO settings.

This applies to any and all lists that are hosted anywhere on GitHub.

**Comment by DandelionSprout** [comment]
Since the problem affects all list repos everywhere on GitHub, and because I've as of recently begun discouraging users from subscribing to my lists directly from my repo (as I recommend FilterLists.com and its maintainer dropdown menu instead), I'll actually choose to simply close the report with this as the reason.
