### ISSUE TITLE
Discussion of IP entries in Anti-Malware's Hosts version

### ISSUE THREAD

**Issue by SGirl-Zockt** [DandelionSprout/adfilt#919]
Hey, can you please remove this from your list...
  [i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 22000 exact domains and 0 ABP-style domains (ignored 7 non-domain entries)
      Sample of non-domain entries:
        - "5.8.47.3"
        - "190.238.183.5"
        - "85.239.33.9"
        - "113.116.89.1"
        - "182.116.104.6"

**Comment by DandelionSprout** [comment]
I remember faintly from around 2020 that IPs in the domains list version was intentional, just in case someone tried to use that list version with software that supported IP blocking. On top of that, non-existent community communication by Pi-hole devs meant I couldn't rule out that Pi-Hole supported such IP blocking.

As it stands, I'm inclined to let the IPs remain, but could reconsider if any domains blocking tools out there were to discard entire lists with unsupported entries (There was a similar incident involving DNSMASQ last week).

**Comment by DandelionSprout** [comment]
Bonus question, since I'm really that much clueless about Pi-hole log files: Is the log info in your (SGirl-Zockt) OP post from Pi-hole, or from another software tool?

**Comment by SGirl-Zockt** [comment]
This is from the Pihole,

If you run pihole -g for a Gravety update then you see it

**Comment by DandelionSprout** [comment]
Presuming you've applied the Pi-hole update that allegedly re-added support for `||`-type lists, can you try to change https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt with https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt , and see if the latter's log output becomes any shorter/better?

**Comment by DandelionSprout** [comment]
>*"can you try to change (…)"*

I'll take that as a no.
