### ISSUE TITLE
pCloud broken website

### ISSUE THREAD

**Issue by tosziro** [DandelionSprout/adfilt#942]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

pCloud.com cloud service website were not working correctly until I added to whitelist "pcdn-my.pcloud.com" and "pcdn-e.pcloud.com". 

### Which adblocker(s) did you use when testing this?

AdGuard Home

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt

### Which browser(s) did you use when testing this?

Firefox (incl. LibreFox)

### Which OS(s) did you use when testing this?

Windows 11

**Comment by DandelionSprout** [comment]
It's hard to tell 100% sure what is going on. From what I can tell from various IP info sites, Pcloud seems to have moved pretty recently from 45.131.244.10 (A pretty safe IP) to 172.255.6.177 (On a server that hosts pretty much only malware; https://securitytrails.com/list/ip/172.255.6.107 lists some examples). Additionally, at least on my PC in Norway across at least 2 browsers with no DNS-blocking, scripts and images completely fail to load on their homepage.

I am certainly tempted to assume that the cloud service has been compromised due to this. I'd have considered moving the cloud files you have there to another service, unless things miraculously get better (and that their websites properly load) within the next 48 hours.

**Comment by DandelionSprout** [comment]
Okay, so, the broken site was because I had forgot I had "AdGuard for Windows" still turned on. Nevertheless, this is going to take a while, potentially some days, to truly test in detail.
