### ISSUE TITLE
Avast & Norton

### ISSUE THREAD

**Issue by TotalImportance8529** [DandelionSprout/adfilt#950]
## Which entry/entries are you submitting?

Norton 
`https://norton.com/`
`https://lifelock.norton.com/`
`https://www.reputationdefender.com/`
`https://www.gendigital.com/us/en/`
`https://www.avira.com/`
Avast and brands belongs to it
`https://www.avast.com/index`
`https://www.avg.com/en-ww/homepage`
`https://www.ccleaner.com/`
`https://www.hidemyass.com/en-us/index`
`https://www.i-dont-care-about-cookies.eu/`
## Which things do they block, hide, or unbreak?

Avast and Norton, these two antivirus are malware themselves.

Scareware,  trying to scaring user in their upsell notifications (Avast and Norton)
4 : 15
`https://www.youtube.com/watch?v=du0hRZnjljA`
`https://www.reddit.com/r/assholedesign/comments/vop6q7/norton_scared_the_shit_out_of_me_before_i/` 

Browser hijacker, automatically open  extensions' web store page (Avast)
`https://forum.avast.com/index.php?topic=323896.0` 

PUP, bundle antivirus (Avast) and install cryptominer without permission (Norton)
`https://www.techspot.com/news/77949-ccleaner-could-install-avast-anti-virus-without-permission.html` 
`https://www.theverge.com/2022/1/7/22869528/norton-crypto-miner-security-software-reaction` 

Spyware, collect and sell user data, including browsing data : 
`https://www.kaspersky.com/blog/is-avast-safe/46519/`

Have a lot of controversies (Norton) : 
`https://en.wikipedia.org/wiki/Gen_Digital#Security_concerns_and_controversies`

## Which of my lists are you submitting it to?
💊 Dandelion Sprout's Anti-Malware List
## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s):

Adblocker version(s): 1.52.2

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock filters
- uBlock filters – Ads
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Quick fixes
- uBlock filters – Unbreak

EasyList

AdGuard URL Tracking Protection

Block Outsider Intrusion into LAN

EasyPrivacy

Online Malicious URL Blocklist

Phishing URL Blocklist

EasyList – Annoyances
- EasyList – Chat Widgets
- EasyList – Newsletter Notices
- EasyList – Notifications
- EasyList – Other Annoyances
- EasyList – Social Widgets
- EasyList/uBO – Cookie Notices
  - EasyList – Cookie Notices
  - uBlock filters – Cookie Notices

uBlock filters – Annoyances

💊 Dandelion Sprout's Anti-Malware List

EasyList China

## (Optional) Which browser(s) and version did you use?

Kiwi Browser 116.0.5845.240

**Comment by DandelionSprout** [comment]
As much as I hate the guts of Avast and AVG (though not as quite as much as I hate McAfee), virtually none of the listed sites can be blocked because there's (unfortunately?) enough quite a few people who still use such tools and would likely complain if I block them outright.

It would ***definitely*** be a No Deal to block `i-dont-care-about-cookies.eu`, who although development on his (Daniel Kladnik) extensions and list seems to have slowed down a lot, is still a beloved adblock list (including by me).

I have precedence of blocking opt-out antivirus options in downloaders, and specific antivirus softwares known to change the default search engines, but blocking antivirus companies *outright* would raise *waaaaaaaay* too big eyebrows, and as such I must decline this outright. You are welcome to write new issues for when installers attempt to bundle any of those companies, however.
